# Generated by Django 4.2.3 on 2023-07-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fechaDeInicio', models.DateField(blank=True, max_length=255)),
                ('fechaDeFin', models.DateField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Curso',
                'db_table': 'Curso',
            },
        ),
    ]
