# Generated by Django 4.2.3 on 2023-07-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppArg40SB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('apellido', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('dni', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='fechaDeFin',
            field=models.DateField(blank=True),
        ),
    ]
