# Generated by Django 4.2.3 on 2023-07-17 22:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppArg40SB', '0002_estudiante_alter_curso_fechadefin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelTable(
            name='estudiante',
            table='Estudiante',
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeInscripcion', models.DateField(blank=True, default=datetime.datetime.now)),
                ('estado', models.CharField(blank=True, default='Aceptada', max_length=255)),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppArg40SB.curso')),
                ('estudiante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppArg40SB.estudiante')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'Inscripcion',
            },
        ),
    ]
