# Generated by Django 4.2.3 on 2023-07-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppArg40SB', '0003_alter_curso_options_alter_estudiante_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(blank=True, choices=[('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Pendiente', 'Pendiente')], default='Aceptada', max_length=45),
        ),
    ]
