# Generated by Django 4.2.3 on 2023-07-17 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppArg40SB', '0004_alter_inscripcion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fechaDeNacimiento',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fechaDeInicio',
            field=models.DateField(blank=True),
        ),
    ]
