# Generated by Django 4.2.3 on 2023-07-18 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppArg40SB', '0005_estudiante_fechadenacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fechaDeFin',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fechaDeInicio',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
