# Generated by Django 4.2.3 on 2023-07-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppArg40SB', '0006_alter_curso_fechadefin_alter_curso_fechadeinicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='dni',
            field=models.IntegerField(blank=True, default=1000000),
        ),
    ]
